
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mosquitto:
    build:
      context: ./backend/mosquitto
      dockerfile: Dockerfile
    image: custom-mosquitto:2.0.21
    container_name: mosquitto
    ports:
      - "1883:1883"
    restart: unless-stopped

  mqttReceiver:
    build:
      context: ./backend/mqttReceiver
      dockerfile: Dockerfile
    image: custom-mqtt-receiver:latest
    container_name: mqttReceiver
    depends_on:
      - mosquitto
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    restart: unless-stopped

  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    image: zdravoziv-backend:latest
    container_name: zdravoziv-backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - mosquitto
    environment:
      - MONGO_URI=mongodb+srv://root:hojladrijadrom@zdravozivpodjetja.1hunr7p.mongodb.net/?retryWrites=true&w=majority&appName=ZdravoZivPodjetja
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    image: zdravoziv-frontend:latest
    container_name: zdravoziv-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  mobile_builder:
    build:
      context: ./frontend/app/mobile_app
      dockerfile: Dockerfile
    image: zdravoziv-mobile-builder:latest
    container_name: mobile_builder
    volumes:
      - ./apk_output:/output
    command: >
      bash -c "
        cd /app &&
        flutter pub get &&
        flutter build apk --release &&
        cp build/app/outputs/flutter-apk/app-release.apk /output/app-release.apk &&
        chmod a+rw /output/app-release.apk
      "
    restart: "no"

  apk_installer:
    build:
      context: ./apk_installer
      dockerfile: Dockerfile
    container_name: apk_installer
    network_mode: "host"           # so adb can see your device on the LAN
    volumes:
      - ./apk_output:/apk_output   # mount the APK output dir
    environment:
      - DEVICE_IP=${DEVICE_IP}
    depends_on:
      - mobile_builder
    # because ENTRYPOINT is ["bash","-c"], we can just pass the same -c script here:
    command: |
      "
        echo 'Povežem se na napravo…';
        adb connect ${DEVICE_IP}:5555;
        sleep 5;
        adb devices;
        echo 'Instaliram APK…';
        adb install -r /apk_output/app-release.apk;
        echo 'Namestitev končana!';
        adb disconnect ${DEVICE_IP}:5555;
      "

volumes:
  mongo-data:
  apk_output:
