version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    image: custom-mosquitto:2.0.21
    container_name: mosquitto
    ports:
      - "1883:1883"
    restart: unless-stopped

  mqttReceiver:
    build:
      context: ./mqttReceiver
      dockerfile: Dockerfile
    image: custom-mqtt-receiver:latest
    container_name: mqttReceiver
    depends_on:
      - mosquitto
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    restart: unless-stopped

  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    image: zdravoziv-backend:latest
    container_name: zdravoziv-backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - mosquitto
    environment:
      - MONGO_URI=mongodb+srv://root:hojladrijadrom@zdravozivpodjetja.1hunr7p.mongodb.net/?retryWrites=true&w=majority&appName=ZdravoZivPodjetja
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    image: zdravoziv-frontend:latest
    container_name: zdravoziv-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  mobile_builder:
    build:
      context: ./frontend/app/mobile_app
      dockerfile: Dockerfile
    image: zdravoziv-mobile-builder:latest
    container_name: mobile_builder
    # na lokalni mapi ./apk_output bo shranjen app-release.apk
    volumes:
      - ./apk_output:/out
    entrypoint: ["sh", "-c"]
    command: >
      flutter build apk --release &&
      cp build/app/outputs/flutter-apk/app-release.apk /out/app-release.apk

volumes:
  mongo-data:
  apk_output:
