version: '3.8'
services:

  mosquitto:
    build:
      context: ./backend/mosquitto
      dockerfile: Dockerfile
    image: custom-mosquitto:2.0.21
    container_name: zdrv_mosquitto
    ports:
      - "1883:1883"
    restart: unless-stopped

  mqttReceiver:
    build:
      context: ./backend/mqttReceiver
      dockerfile: Dockerfile
    image: custom-mqtt-receiver:latest
    container_name: zdrv_receiver
    depends_on:
      - mosquitto
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: zdrv_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    image: zdravoziv-backend:latest
    container_name: zdrv_backend
    depends_on:
      - mongodb
      - mosquitto
      - mqttReceiver
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://root:hojladrijadrom@zdravozivpodjetja.1hunr7p.mongodb.net/?retryWrites=true&w=majority&appName=ZdravoZivPodjetja
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    image: zdravoziv-frontend:latest
    container_name: zdrv_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  mongo-data:
