
services:

  # Mosquitto MQTT broker
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    image: custom-mosquitto:2.0.21
    container_name: zdrv_mosquitto
    ports:
      - "1883:1883"
    restart: unless-stopped

  # MQTT Receiver
  mqttReceiver:
    build:
      context: ./mqttReceiver
      dockerfile: Dockerfile
    image: custom-mqtt-receiver:latest
    container_name: zdrv_receiver
    depends_on:
      - mosquitto
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    restart: unless-stopped

  # MongoDB
  mongo:
    image: mongo:6
    container_name: zdrv_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # Node.js Backend
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: zdravoziv-backend:latest
    container_name: zdrv_backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - mosquitto
    env_file:
      - /.env
    restart: unless-stopped

volumes:
  mongo-data:
