name: mobile_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.0.0
  geolocator: ^11.0.0
  sensors_plus: ^3.0.3
  pedometer: ^4.0.1
  shared_preferences: ^2.2.2
  camera: ^0.10.5
  path_provider: ^2.0.15
  image_picker: ^1.0.4
  http: ^1.0.0
  path: ^1.8.3

  cupertino_icons: ^1.0.8
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  google_maps_flutter: ^2.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/ca.crt
    - assets/FitOffice_logo_new.jpeg

  
