name: Run Backend Tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/api

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run only user.test.js
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
          MQTT_URI: mqtt://192.168.0.11:1883
          BROKER_HOST: "192.168.0.11"
          BROKER_PORT: 1883
          TOPIC: sensors/test
          TWO_FA_TOPIC_PREFIX: 2fa/confirm/
        run: npx jest tests/user.test.js --verbose --runInBand --forceExit
